name: "Continuous Integration"

on:
  pull_request:
    branches:
      - "*.x"
  push:

env:
  fail-fast: false

jobs:
  unit-tests:
    name: "Unit tests"
    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v3"
        with:
          dependency-versions: "highest"

      - name: "Test fixes"
        run: "vendor/bin/phpunit --coverage-text"
